<a href="https://colab.research.google.com/github/ThaironyDev/Pandas_OI/blob/main/Pandas_IO_Exerc%C3%ADcios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Para saber mais: erro de encoding - Como resolver?

Quando tentamos abrir um arquivo que foi salvo com um tipo de formatação de caracteres diferente do padrão universal UTF-8, podemos ter um erro de encoding. Para resolver essa questão, podemos usar a biblioteca chardet para detectar o encoding de um arquivo. Podemos ver que o tipo de codificação do arquivo é 'ascii' que por sua vez é compatível com a 'UTF-8'.

In [1]:
import chardet
import requests
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/superstore_data_ponto_virgula.csv'
response = requests.get(url)
if response.status_code == 200:
  content = response.content
  encoding_info = chardet.detect(content)
  print(encoding_info)
else:
  print('Falha ao obter o aquivo da URL.')

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

##Desafio: lendo dados com vários parâmetros

In [2]:
import chardet, requests, csv, pandas as pd

>Verificando a codificação do arquivo.

In [3]:
response = requests.get(url)
if response.status_code == 200:
  content = response.content
  info_encoding = chardet.detect(content)
  print(info_encoding)
else:
  print('Falha ao obter o aquivo da URL.')

{'encoding': 'ascii', 'confidence': 1.0, 'language': ''}

>Verificando se o arquivo é separado por virgula.

In [4]:
encoding = info_encoding['encoding']
sniffer = csv.Sniffer()
dialect = sniffer.sniff(content.decode(encoding))
separador = dialect.delimiter
df = pd.read_csv(url, delimiter=separador, encoding=encoding)

print(f"Delimitador detectado: '{separador}'")

Delimitador detectado: ';'

>Desconsiderando as 3 primeiras linhas.

In [5]:
df = pd.read_csv(url, skiprows=3, sep=separador)
df.head()

,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0.1,134,...,15,2,30,1.1,3,2.1,5,2.2,0.2,0.3
0,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
1,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0
2,7348,1958,PhD,Single,71691.0,0,0,3/17/2014,0,336,...,240,32,43,1,4,7,5,2,1,0
3,4073,1954,2n Cycle,Married,63564.0,0,0,1/29/2014,0,769,...,15,34,65,1,10,10,7,6,1,0
4,1991,1967,Graduation,Together,44931.0,0,1,1/18/2014,0,78,...,0,0,7,1,2,1,3,5,0,0

In [6]:
df = pd.read_csv(url, skipfooter=9, engine='python', sep=separador)
df.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

## Desafio: lendo dados de outro link

>Neste trecho dividimos nosso código em 3 partes além de importar a biblioteca do pandas.
de posse da string que pertence a planilha que está no goolge planilhas podemos instanciar as variáveis sheet_id e url usando os parâmetros necessários de acesso a API na variável param.

In [7]:
import pandas as pd
'https://docs.google.com/spreadsheets/d/1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw/edit?usp=sharing'
sheet_id = '1pvBoLyX8kP0TjtUbadVMGdTl4yzm6bHMThhPiqCVtpw'
param = '/gviz/tq?tqx=out:csv&sheet'
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}{param}'

>Efetuamos a leitura do arquivo.

In [8]:
emissoes_carbono_mundo = pd.read_csv(url)

>Salvamos no formato csv.

In [9]:
emissoes_carbono_mundo.to_csv('emissoes_carbono_mundo.csv', index=False, sep=',')

>Confirmamos se o arquivo foi salvo corretamente.

In [10]:
pd.read_csv('emissoes_carbono_mundo.csv').head()

,Country Name,country_code,Region,Indicator Name,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2019.1
0,Aruba,ABW,Latin America & Caribbean,CO2 emissions (metric tons per capita),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,South Asia,CO2 emissions (metric tons per capita),191.745.115,167.681.579,95.957.742,8.472.111,75.545.827,68.467.956,...,29.650.624,259.295.334,18.562.366,146.235.617,172.896.741,149.789.334,131.694.556,1.632.953,159.824.372,159.824.372
2,Angola,AGO,Sub-Saharan Africa,CO2 emissions (metric tons per capita),553.661.955,544.538.649,543.557.223,70.898.423,836.804.405,912.141.485,...,985.522.312,950.695.879,1.036.293.852,1.099.779.111,113.504.405,1.031.811.348,81.330.073,777.674.934,792.137.069,792.137.069
3,Albania,ALB,Europe & Central Asia,CO2 emissions (metric tons per capita),1.819.541.634,124.281.022,683.699.826,638.307.036,645.355.189,605.436.253,...,166.942.319,150.324.046,1.533.630.039,1.668.337.371,160.377.515,1.557.664.358,1.788.786.074,1.782.738.948,169.224.832,169.224.832
4,Andorra,AND,Europe & Central Asia,CO2 emissions (metric tons per capita),7.521.831.658,723.537.924,69.630.787,6.724.177.518,6.541.578.914,6.733.479.486,...,5.850.886.105,5.944.654.173,5.942.800.412,5.807.127.723,6.026.181.822,6.080.600.282,6.104.133.912,6.362.975.399,6.481.217.432,6.481.217.432

##Desafio: normalizando o JSON obtido na API

>Para saber mais: obtendo arquivos JSON de APIs

---
Primeiramente acessamos os dados via requisição HTTP para a API da fruityvice.com. Depois, verificamos o status da requisição. Em seguida, instanciamos o conteúdo de interesse em uma variável. Usando a biblioteca json, carregamos esses dados que estão em formato JSON para um formato de dicionário Python. Por fim, usando o método pd.json_normalize, criamos um DataFrame normalizado a partir deste dicionário e apresentamos suas 5 primeiras linhas.

In [11]:
import requests, json, pandas as pd

In [12]:
url = 'https://fruityvice.com/api/fruit/all'
response = requests.get(url)
response.status_code
content = response.content
dados_dict = json.loads(content)
dados_frutas = pd.json_normalize(dados_dict)
dados_frutas.head()

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.0,18.0,18.0,0.0
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.4,5.4,5.5,0.8
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.2,17.2,22.0,1.0
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.2,2.6,3.9,0.9
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.1,10.0,15.0,0.4

##Desafio: lendo uma tabela de uma página web

> Neste caso após importar as libs de interesse realizamos a requisição http, depois de posse do conteúdo html instanciamos a variável dados_habitantes com a tabela de interesse usando o método pd.read_html()[], por fim eliminamos a coluna adicional correspondentes aos índices do arquivo e apresentamos as 5 primeiras linhas.

In [13]:
import requests, pandas as pd
url = 'https://pt.wikipedia.org/wiki/Lista_de_pa%C3%ADses_por_popula%C3%A7%C3%A3o'
response = requests.get(url)
response.status_code
content = response.content
dados_habitantes = pd.read_html(content)[0]
dados_habitantes.drop('Unnamed: 0', axis=1, inplace=True)
dados_habitantes.head()

,Posição,País (ou território dependente),Estimativa da ONU,Data,Estimativa Oficial
0,1,Índia,1 429 921 746,2023,Estimativa oficial
1,2,China,1 426 391 281,2023,Censo oficial
2,3,Estados Unidos,339 987 103,2023,Censo oficial
3,4,Indonésia,277 184 719,2023,Estimativa oficial
4,5,Paquistão,240 215 932,2023,Estimativa oficial

##Desafio: manipulando um banco de dados

>Para garantir a conpatibilidade dos comandos vamos usar uma versão do sqlalchemy inferior a 2. Por tanto o primeiro passo é prepararo o ambiente.

In [14]:
!pip install --upgrade 'sqlalchemy<2'
import sqlalchemy, pandas as pd
sqlalchemy.__version__

Collecting sqlalchemy<2
  Downloading SQLAlchemy-1.4.50-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.0 MB/s eta 0:00:00
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy<2) (3.0.0)
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.22
    Uninstalling SQLAlchemy-2.0.22:
      Successfully uninstalled SQLAlchemy-2.0.22
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.4.50 which is incompatible.
Successfully installed sqlalchemy-1.4.50

'1.4.50'

>Usando as ferramentas do sqlalchemy para criação e gestão do banco de dados.

In [15]:
from sqlalchemy import create_engine, inspect

>Criando um banco de dados local.

---

>Criando o nosso motor de conexão com o banco de dados para isso vamos usar a função create_engine() passando uma string que informa qual SGBD vamos usar e onde será alocada.

---

'sqlite -> SGBD' eo ':///:mermory:' diz respeito a uma espaço na memória local.

In [16]:
engine = create_engine('sqlite:///:memory')

In [17]:
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)
dados.to_sql('clientes', engine, index=False)

438463

>Verificando se a tabela foi criada com exito.

In [18]:
inspetor = inspect(engine)
inspetor.get_table_names() # Exibe os nomes das tabelas que constam no banco de dados.

['clientes']

>Fazendo uma consulta ao banco de dados.

In [19]:
query = 'SELECT * FROM clientes'
pd.read_sql(query, con=engine).head()
#ou
pd.read_sql_table('clientes', engine).head()
#Note que na primeira temos uma consulta SQL e na segunda temos um metodo onde informamos a tabela que queremos visualizar.

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

>Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.

In [20]:
query = 'UPDATE clientes SET Rendimento_anual = 300000 WHERE ID_Cliente == 6840104'
with engine.connect() as conn:
  conn.execute(query)
query = 'SELECT *  FROM clientes WHERE ID_Cliente == 6840104'
pd.read_sql(query, con=engine).head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

>Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.

In [21]:
query = 'DELETE FROM clientes WHERE ID_Cliente = 5008809'
with engine.connect() as conn:
  conn.execute(query)
pd.read_sql_table('clientes', engine).head(6)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008810,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
5,5008811,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

>Criar um novo registro de cliente seguindo as especificações abaixo:

---


* ID_Cliente: 6850985
* Idade: 33
* Grau_escolaridade: Doutorado
* Estado_civil: Solteiro
* Tamanho_familia: 1
* Categoria_de_renda: Empregado
* Ocupacao: TI
* Anos_empregado: 2
* Rendimento_anual: 290000
* Tem_carro: 0
* Moradia: Casa/apartamento próprio

In [22]:
# @title
query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, ' + \
        'Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) ' + \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/Apartamento próprio")'

with engine.connect() as conn:
  conn.execute(query)
query = 'SELECT * FROM clientes WHERE ID_Cliente = 6850985'
pd.read_sql(query, con=engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/Apartamento próprio